export const SETFORMDATA = "SETFORMDATA";
export const SET_DATA_OF_API_BIRTH = "SET_DATA_OF_API_BIRTH";
export const SET_DATA_OF_API_ASTRO = "SET_DATA_OF_API_ASTRO";
export const SET_DATA_OF_API_PANCHANG = "SET_DATA_OF_API_PANCHANG";